# --------------------------
# Ansible Playbook
# Configure unix daemon services for rsyslog
# Creates pipeline into Graylog from client endpoints
# systemd: rsyslog.unit
# taken from: https://quant.one/gain-control-over-log-events-with-graylog-and-ansible
# --------------------------

- hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Configure services for ryslog
      block:
        - name: Install rsyslog
          apt:
            name: rsyslog
            state: present

        - name: Set Default Config Params
          copy:
            src: rsyslog.conf
            dest: /etc/rsyslog.conf
            force: true

        - name: Configure System Service
          systemd:
            name: rsyslog
            enabled: yes
            state: started

# --------------------------
